### ISSUE TITLE
Bug: home text overlaps navigation

### ISSUE THREAD

**Issue by quietbits** [hollyjrm/alt-portfolio#3]
When scrolling the Home page text overlaps the navigation. You can easily fix this by bumping up z-index for the nav. Don't be afraid to use larger numbers. It might be beneficial to group "levels" of z-index for different use cases. For example, 100s for navigation, 200s for modals, etc. The portfolio doesn't have many overlapping elements, but a more complex website might.

![image](https://user-images.githubusercontent.com/7346473/153520008-75fbf49c-1a4f-4008-9b7a-cb594edbaaf9.png)

**Comment by hollyjrm** [comment]
Thanks! I didn't notice that :) Just changed it now.
